const calendarData = {
    globalHeader: "ປະຕິທິນເຜົ່າຍວນ, ເຜົ່າລື້, ເຜົ່າຜູ້ນ້ອຍ, ເຜົ່າລາວເທິງ, ຄຳນວນໂດຍ ທ່ານໜານນວນ ລັດຕະນະວົງ ບ້ານຫຼວງ ເມືອງຫຼວງນ້ຳທາ",
    months: [
        {
            nameLao: "ມັງກອນ",
            nameEng: "JANUARY", 
            headerDetails: "ເດືອນມັງກອນ (1) ປີມະເສງ. ປີຮັບໃສ້. ສັດຕະສົກ. ອະທິກະມາດ, ປົກະຕິວາດ, ປົກະຕິສຸກທີນ ພ.ສ. 2568- ຈ.ສ.1387-88. ຄ.ສ. 2026",
            startDay: 4, // Thursday
            footerText: [
                "1 ປີໃໝ່ສາກົນ. ຄ.ສ 2026",
                "19 ບຸນກຸດຈີນ.",
                "20 ວັນສ້າງຕັ້ງກອງທັບປະຊາຊົນລາວຄົບຮອບ 77 ປີ (20/01/1949)"
            ],
            days: [
                { date: 1, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. ສາມ", prediction: "ຮັບໃຄ້ - ຮັບໃຂ້" },
                { date: 2, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ຮວ່າຍໃຈ້ - ຮັບຕາຍ" },
                { date: 3, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເມິງເປົ້າ - ຂວໍ້າໄດ", special: "red" },
                { date: 4, lunar: "ແຮມ 1 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເປືກຍີ - ໄສເຈົ້າ" },
                { date: 5, lunar: "ແຮມ 2 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກັດເໝົ້າ - ໄສເສຍ" },
                { date: 6, lunar: "ແຮມ 3 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກົດສີ - ທ້ວາປາວ" },
                { date: 7, lunar: "ແຮມ 4 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ຮ້ວງໃສ້ - ສ້ຽວປາວ" },
                { date: 8, lunar: "ແຮມ 5 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເຕົ່າສະຫ້ງາ - ເກົ້າກອງ" },
                { date: 9, lunar: "ແຮມ 6 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກ່າມົດ - ຮອງຟືນ" },
                { date: 10, lunar: "ແຮມ 7 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກາບສັນ - ຟືນດອກ" },
                { date: 11, lunar: "ແຮມ 8 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ຮັບເຣົ້າ - ຟືມດາຍ", special: "red" },
                { date: 12, lunar: "ແຮມ 9 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ຮວາຍເສັດ - ສຸພັກ" },
                { date: 13, lunar: "ແຮມ 10 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເມິງໃຄ້ -  ຮັບໄຂ້" },
                { date: 14, lunar: "ແຮມ 11 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເປີກໃຈ້ - ຮັບຕາຍ" },
                { date: 15, lunar: "ແຮມ 12 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກັດເປົ້າ - ຂວໍ້າໄດ" },
                { date: 16, lunar: "ແຮມ 13 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ກົດຍີ - ໄສເຈົ້າ" },
                { date: 17, lunar: "ແຮມ 14 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ຮ້ວງເໝົ້າ - ໄສເສຍ" },
                { date: 18, lunar: "ແຮມ 15 ຄ່ຳ ດ. ສາມ", prediction: "ມື້ເຕົ່າສີ - ທ້ວາຽປາວ", special: "red" },
                { date: 19, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກ່າໃສ້ - ເກົ້າກອງ" },
                { date: 20, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກາບສະຫງ້າ - ຮອງຟືນ" },
                { date: 21, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ຮັບມົດ - ຝີນດອກ" },
                { date: 22, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ຮວາຍສັນ - ຟືນດາຍ" },
                { date: 23, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ເມີງເຮົ້າ - ສຸພັກ" },
                { date: 24, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ເປິກເສັດ - ຮັບໄຂ້" },
                { date: 25, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກັດໃຄ້ - ຮັບຕາຍ" },
                { date: 26, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກົດໃຈ້ - ຂວໍ້າໄດ", special: "red" },
                { date: 27, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ຮ້ວງເປົ້າ - ໄສເຈົ້າ" },
                { date: 28, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ເຕົ່າຍີ - ໄສເສຍ" },
                { date: 29, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກ່າເໝົ້າ - ທ້ວາຽປາວ" },
                { date: 30, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ກາບສີ - ສ້ຽວປາວ" },
                { date: 31, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. ສີ່", prediction: "ມື້ຮັບໃສ້ - ເກົ້າກອງ" }
            ]
        },
        {
            nameLao: "ກຸມພາ",
            nameEng: "FEBRUARY",
            headerDetails: "ເດືອນກຸມພາ (2) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2568- ຈ.ສ.1387. ຄ.ສ. 2026",
            startDay: 5, // Friday
            footerText: [
                "1 ວັນສ້າງຕັ້ງກຳມະບານລາວ ຄົບຮອບ 60 ປີ (1/2/1966)",
                "2 ວັນບຸນມະຄະບູຊາ (ມື້ວາຍສະງ້າ) - ຂຶ້ນ 15 ຄ່ຳ ຄ.ສ 1628 ແລະ ມາກະບູຊາ",
                "2 ບຸນນະມັດສະການພະທາດສີໂຄດຕະບອງ",
                "2 ບຸນນະມັດສະການພະທາດອິງຮັງ"
            ],
            days: [
                { date: 1, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 6", prediction: "ມື້ວາຍສະງ້າ - ພັນຕາຍ", special: "red" },
                { date: 2, lunar: "ແຮມ 1 ຄ່ຳ ດ. 6", prediction: "ມື້ເມັງມົດ - ສຸກພັກ" },
                { date: 3, lunar: "ແຮມ 2 ຄ່ຳ ດ. 6", prediction: "ມື້ປືກສັນ - ຮັບໄຊ້" },
                { date: 4, lunar: "ແຮມ 3 ຄ່ຳ ດ. 6", prediction: "ມື້ກັດເລົ້າ - ຮັບຕາຍ" },
                { date: 5, lunar: "ແຮມ 4 ຄ່ຳ ດ. 6", prediction: "ມື້ກົດເສັດ - ງົວຕາຍ" },
                { date: 6, lunar: "ແຮມ 5 ຄ່ຳ ດ. 6", prediction: "ມື້ຮ້ວງໄກ້ - ໃສ່ເຈົ້າ" },
                { date: 7, lunar: "ແຮມ 6 ຄ່ຳ ດ. 6", prediction: "ມື້ເຕົ່າໃຈ - ໃສ່ເສຍ" },
                { date: 8, lunar: "ແຮມ 7 ຄ່ຳ ດ. 6", prediction: "ມື້ກ່າເປົ້າ - ຫົວວາຍປ່າວ" },
                { date: 9, lunar: "ແຮມ 8 ຄ່ຳ ດ. 6", prediction: "ມື້ກາບຍີ - ສ້ຽວປ່າວ", special: "red" },
                { date: 10, lunar: "ແຮມ 9 ຄ່ຳ ດ. 6", prediction: "ມື້ດັບເໝົ້າ - ເຕົ້າກອງ" },
                { date: 11, lunar: "ແຮມ 10 ຄ່ຳ ດ. 6", prediction: "ມື້ຮາຍສີ - ຮອງຟືນ" },
                { date: 12, lunar: "ແຮມ 11 ຄ່ຳ ດ. 6", prediction: "ມື້ເມັງໃສ້ - ພັນດອກ" },
                { date: 13, lunar: "ແຮມ 12 ຄ່ຳ ດ. 6", prediction: "ມື້ປືກສະງ້າ - ພັນຕາຍ" },
                { date: 14, lunar: "ແຮມ 13 ຄ່ຳ ດ. 6", prediction: "ມື້ກັດເມັດ - ສຸກພັກ" },
                { date: 15, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 6", prediction: "ມື້ກົດສັນ - ຮັບໄຊ້", special: "red" },
                { date: 16, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 6", prediction: "ມື້ຮ້ວງເລົ້າ - ຄວາຍຕາຍ", special: "red" },
                { date: 17, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 7", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເຈົ້າ" },
                { date: 18, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 7", prediction: "ມື້ກ່າໄກ້ - ໃສ່ເສຍ" },
                { date: 19, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 7", prediction: "ມື້ກາບໃຈ - ຫົວວາຍປ່າວ" },
                { date: 20, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 7", prediction: "ມື້ດັບເປົ້າ - ສ້ຽວປ່າວ" },
                { date: 21, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 7", prediction: "ມື້ຮາຍຍີ - ເຕົ້າກອງ" },
                { date: 22, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 7", prediction: "ມື້ເມັງເໝົ້າ - ຮອງຟືນ" },
                { date: 23, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 7", prediction: "ມື້ປືກສີ - ພັນດອກ" },
                { date: 24, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 7", prediction: "ມື້ກັດໃສ້ - ພັນຕາຍ", special: "red" },
                { date: 25, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 7", prediction: "ມື້ກົດສະງ້າ - ສຸກພັກ" },
                { date: 26, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 7", prediction: "ມື້ຮ້ວງເມັດ - ຮັບໄຊ້" },
                { date: 27, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 7", prediction: "ມື້ເຕົ່າສັນ - ຮັບຕາຍ" },
                { date: 28, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 7", prediction: "ມື້ກ່າເລົ້າ - ຄວາຍຕາຍ" }
            ]
        },
        {
             nameLao: "ມີນາ",
             nameEng: "MARCH",
             headerDetails: "ເດືອນມີນາ (3) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖิน ພ.ສ. 2568- ຈ.ສ.1387. ຄ.ສ 2026",
             startDay: 0, // Sunday
             footerText: [
                "8 ວັນແມ່ຍິງສາກົນ ຄົບຮອບ 116 ປີ (8/3/1910)",
                "3 ບຸນພະເວດ (ບຸນພະມະຫາຊາດ)",
                "22 ວັນສ້າງຕັ້ງພັກປະຊາຊົນປະຕິວັດລາວ ຄົບຮອບ 71 ປີ (22/3/1955)"
             ],
             days: [
                { date: 1, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 7", prediction: "ມື້ກາບເສັດ - ໃສ່ເຈົ້າ" },
                { date: 2, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 7", prediction: "ມື້ດັບໄກ້ - ຄວ້າີໄດ" },
                { date: 3, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 7", prediction: "ມື້ຮາຍໃຈ - ໃສ່ເສຍ", special: "red" },
                { date: 4, lunar: "ແຮມ 1 ຄ່ຳ ດ. 7", prediction: "ມື້ເມັງເປົ້າ - ຫົວວາຍປ່າວ" },
                { date: 5, lunar: "ແຮມ 2 ຄ່ຳ ດ. 7", prediction: "ມື້ປືກຍີ - ສ້ຽວປ່າວ" },
                { date: 6, lunar: "ແຮມ 3 ຄ່ຳ ດ. 7", prediction: "ມື້ກັດເໝົ້າ - ເຕົ້າກອງ" },
                { date: 7, lunar: "ແຮມ 4 ຄ່ຳ ດ. 7", prediction: "ມື້ກົດສີ - ຮອງຟືນ" },
                { date: 8, lunar: "ແຮມ 5 ຄ່ຳ ດ. 7", prediction: "ມື້ຮ້ວງໃສ້ - ພັນດອກ", special: "red" },
                { date: 9, lunar: "ແຮມ 6 ຄ່ຳ ດ. 7", prediction: "ມື້ເຕົ່າສະງ້າ - ພັນຕາຍ" },
                { date: 10, lunar: "ແຮມ 7 ຄ່ຳ ດ. 7", prediction: "ມື້ກ່າເມັດ - ສຸກພັກ" },
                { date: 11, lunar: "ແຮມ 8 ຄ່ຳ ດ. 7", prediction: "ມື້ກາບສັນ - ຮັບໄຊ້", special: "red" },
                { date: 12, lunar: "ແຮມ 9 ຄ່ຳ ດ. 7", prediction: "ມື້ດັບເລົ້າ - ຮັບຕາຍ" },
                { date: 13, lunar: "ແຮມ 10 ຄ່ຳ ດ. 7", prediction: "ມື້ຮາຍເສັດ - ງົວຕາຍ" },
                { date: 14, lunar: "ແຮມ 11 ຄ່ຳ ດ. 7", prediction: "ມື້ເມັງໄກ້ - ໃສ່ເຈົ້າ" },
                { date: 15, lunar: "ແຮມ 12 ຄ່ຳ ດ. 7", prediction: "ມື້ປືກໃຈ - ໃສ່ເສຍ" },
                { date: 16, lunar: "ແຮມ 13 ຄ່ຳ ດ. 7", prediction: "ມື້ກັດເປົ້າ - ຫົວວາຍປ່າວ" },
                { date: 17, lunar: "ແຮມ 14 ຄ່ຳ ດ. 7", prediction: "ມື້ກົດຍີ - ສ້ຽວປ່າວ" },
                { date: 18, lunar: "ແຮມ 15 ຄ່ຳ ດ. 7", prediction: "ມື້ຮ້ວງເໝົ້າ - ເຕົ້າກອງ", special: "red" },
                { date: 19, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າສີ - ຮອງຟືນ" },
                { date: 20, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າໃສ້ - ພັນດອກ" },
                { date: 21, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບສະງ້າ - ພັນຕາຍ" },
                { date: 22, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບເມັດ - ສຸກພັກ" },
                { date: 23, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສັນ - ຮັບໄຊ້" },
                { date: 24, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງເລົ້າ - ຮັບຕາຍ" },
                { date: 25, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກເສັດ - ງົວຕາຍ" },
                { date: 26, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດໄກ້ - ໃສ່ເຈົ້າ", special: "red" },
                { date: 27, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 8", prediction: "ມື້ກົດໃຈ - ໃສ່ເສຍ" },
                { date: 28, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງເປົ້າ - ຫົວວາຍປ່າວ" },
                { date: 29, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າຍີ - ສ້ຽວປ່າວ", special: "red" },
                { date: 30, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າເໝົ້າ - ເຕົ້າກອງ" },
                { date: 31, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບສີ - ຮອງຟືນ" }
             ]
        },
        {
             nameLao: "ເມສາ",
             nameEng: "APRIL",
             headerDetails: "ເດືອນເມສາ (4) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖิน ພ.ສ. 2568- ຈ.ສ.1387-88. ຄ.ສ 2026",
             startDay: 3, // Wednesday
             footerText: [
                 "1 ປີໃໝ່ສາກົນ ຄ.ສ 2026",
                 "19 ບຸນກຸດຈີນ",
                 "20 ວັນສ້າງຕັ້ງກອງທັບປະຊາຊົນລາວ ຄົບຮອບ 77 ປີ (20/01/1949)"
             ],
             days: [
                 { date: 1, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບໃສ້ - ພັນດອກ" },
                 { date: 2, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສະງ້າ - ພັນຕາຍ", special: "red" },
                 { date: 3, lunar: "ແຮມ 1 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງມົດ - ສຸກພັກ" },
                 { date: 4, lunar: "ແຮມ 2 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກສັນ - ຮັບໄຊ້" },
                 { date: 5, lunar: "ແຮມ 3 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດເລົ້າ - ຮັບຕາຍ" },
                 { date: 6, lunar: "ແຮມ 4 ຄ່ຳ ດ. 8", prediction: "ມື້ກົດເສັດ - ງົວຕາຍ" },
                 { date: 7, lunar: "ແຮມ 5 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງໄກ້ - ໃສ່ເຈົ້າ" },
                 { date: 8, lunar: "ແຮມ 6 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າໃຈ - ໃສ່ເສຍ" },
                 { date: 9, lunar: "ແຮມ 7 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າເປົ້າ - ຫົວວາຍປ່າວ" },
                 { date: 10, lunar: "ແຮມ 8 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບຍີ - ສ້ຽວປ່າວ", special: "red" },
                 { date: 11, lunar: "ແຮມ 9 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບເໝົ້າ - ເຕົ້າກອງ" },
                 { date: 12, lunar: "ແຮມ 10 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສີ - ຮອງຟືນ" },
                 { date: 13, lunar: "ແຮມ 11 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງໃສ້ - ພັນດອກ" },
                 { date: 14, lunar: "ແຮມ 12 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກສະງ້າ - ພັນຕາຍ" },
                 { date: 15, lunar: "ແຮມ 13 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດເມັດ - ສຸກພັກ" },
                 { date: 16, lunar: "ແຮມ 14 ຄ່ຳ ດ. 8", prediction: "ມື້ກົດສັນ - ຮັບໄຊ້", special: "red" },
                 { date: 17, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງເລົ້າ - ຄວາຍຕາຍ" },
                 { date: 18, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 9", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເຈົ້າ" },
                 { date: 19, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 9", prediction: "ມື້ກ່າໄກ້ - ໃສ່ເສຍ" },
                 { date: 20, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 9", prediction: "ມື້ກາບໃຈ - ຫົວວາຍປ່າວ" },
                 { date: 21, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 9", prediction: "ມື້ດັບເປົ້າ - ສ້ຽວປ່າວ" },
                 { date: 22, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 9", prediction: "ມື້ຮາຍຍີ - ເຕົ້າກອງ" },
                 { date: 23, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 9", prediction: "ມື້ເມັງເໝົ້າ - ຮອງຟືນ" },
                 { date: 24, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 9", prediction: "ມື້ປືກສີ - ພັນດອກ" },
                 { date: 25, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 9", prediction: "ມື້ກັດໃສ້ - ພັນຕາຍ", special: "red" },
                 { date: 26, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 9", prediction: "ມື້ກົດສະງ້າ - ສຸກພັກ" },
                 { date: 27, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 9", prediction: "ມື້ຮ້ວງເມັດ - ຮັບໄຊ້" },
                 { date: 28, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 9", prediction: "ມື້ເຕົ່າສັນ - ຮັບຕາຍ" },
                 { date: 29, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 9", prediction: "ມື້ກ່າເລົ້າ - ຄວາຍຕາຍ" },
                 { date: 30, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 9", prediction: "ມື້ກາບເສັດ - ໃສ່ເຈົ້າ" }
             ]
        },
        {
            nameLao: "ພຶດສະພາ",
            nameEng: "MAY",
            headerDetails: "ເດືອນພຶດສະພາ (5) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 5, // Friday
            footerText: [
                "1 ວັນກຳມະກອນສາກົນ (1/5/1886)",
                "1 ວັນວິສາຂະບູຊາ. ປ່ຽນ ພ.ສ 2569",
                "8 ວັນກາແດງໂລກ (8/5/1828)",
                "20 ລ້ຽງພະຍາຫຼວງໜ້າຂັ້ນ 4 ຄ່ຳ ເດືອນ 8 ຍາວ",
                "23 ລ້ຽງພະຍານ້ອງເມືອງນ້ຳທາ ຂຶ້ນ 7 ຄ່ຳ ເດືອນ 8 ຍາວ ນັບແຕ່ ຄ.ສ 1715 ເປັນຕົ້ນໄປ",
                "24 ວັນຜູ້ ນຳ ແນວລາວຮັກຊາດ ແຫກຄຸກໂພນເຄັງ (24/5/1960)"
            ],
            days: [
                { date: 1, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 7", prediction: "ມື້ຮັບໄຊ້ - ໃສ່ເສຍ", special: "red" },
                { date: 2, lunar: "ແຮມ 1 ຄ່ຳ ດ. 7", prediction: "ມື້ຮອງໄໃຊ້ - ຫົວວາຍ"},
                { date: 3, lunar: "ແຮມ 2 ຄ່ຳ ດ. 7", prediction: "ມື້ເມັງເປົ້າ - ສ້ຽວປ່າວ" },
                { date: 4, lunar: "ແຮມ 3 ຄ່ຳ ດ. 7", prediction: "ມື້ປືກຍີ - ພັນດອກ" },
                { date: 5, lunar: "ແຮມ 4 ຄ່ຳ ດ. 7", prediction: "ມື້ກັດເໝົ້າ - ພັນຕາຍ" },
                { date: 6, lunar: "ແຮມ 5 ຄ່ຳ ດ. 7", prediction: "ມື້ກົດສີ - ພັນຕາຍ" },
                { date: 7, lunar: "ແຮມ 6 ຄ່ຳ ດ. 7", prediction: "ມື້ຮ້ວງໃສ້ - ສຸກພັກ" },
                { date: 8, lunar: "ແຮມ 7 ຄ່ຳ ດ. 7", prediction: "ມື້ເຕົ່າສະງ້າ - ຮັບໄຊ້", special: "red" },
                { date: 9, lunar: "ແຮມ 8 ຄ່ຳ ດ. 7", prediction: "ມື້ກ່າເມັດ - ຮັບຕາຍ", special: "red" },
                { date: 10, lunar: "ແຮມ 9 ຄ່ຳ ດ. 7", prediction: "ມື້ກາບສັນ - ງົວຕາຍ" },
                { date: 11, lunar: "ແຮມ 10 ຄ່ຳ ດ. 7", prediction: "ມື້ດັບເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 12, lunar: "ແຮມ 11 ຄ່ຳ ດ. 7", prediction: "ມື້ຮາຍເສັດ - ໃສ່ເສຍ" },
                { date: 13, lunar: "ແຮມ 12 ຄ່ຳ ດ. 7", prediction: "ມື້ເມັງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 14, lunar: "ແຮມ 13 ຄ່ຳ ດ. 7", prediction: "ມື້ປືກໃຈ - ສ້ຽວປ່າວ" },
                { date: 15, lunar: "ແຮມ 14 ຄ່ຳ ດ. 6", prediction: "ມື້ກັດເປົ້າ - ສ້ຽວປ່າວ" },
                { date: 16, lunar: "ແຮມ 15 ຄ່ຳ ດ. 7", prediction: "ມື້ກົດຍີ - ເຕົ້າກອງ", special: "red" },
                { date: 17, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງເໝົ້າ - ຮອງຟືນ" },
                { date: 18, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າສີ - ພັນດອກ" },
                { date: 19, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າໃສ້ - ພັນຕາຍ" },
                { date: 20, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບສະງ້າ - ຮັບໄຊ້" },
                { date: 21, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບເມັດ - ຮັບຕາຍ" },
                { date: 22, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສັນ - ຄວາຍຕາຍ" },
                { date: 23, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 24, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກເສັດ - ໃສ່ເສຍ", special: "red" },
                { date: 25, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 26, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 8", prediction: "ມື້ກົດໃຈ - ສ້ຽວປ່າວ" },
                { date: 27, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງເປົ້າ - ເຕົ້າກອງ" },
                { date: 28, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າຍີ - ຮອງຟືນ" },
                { date: 29, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າເໝົ້າ - ພັນດອກ" },
                { date: 30, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບສີ - ພັນຕາຍ" },
                { date: 31, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບໃສ້ - ຮັບໄຊ້" }
            ]
        },
        {
            nameLao: "ມິຖຸນາ",
            nameEng: "JUNE",
            headerDetails: "ເດືອນມິຖຸນາ (6) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 1, // Monday
            footerText: [
                "1 ວັນເດັກນ້ອຍສາກົນ ຄົບຮອບ 76 ປີ 1950",
                "1 ວັນປູກຕົ້ນໄມ້ແຫ່ງຊາດ"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 1 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສະງ້າ - ຮັບໄຊ້" },
                { date: 2, lunar: "ແຮມ 2 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງມົດ - ຮັບຕາຍ" },
                { date: 3, lunar: "ແຮມ 3 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກສັນ - ຄວ້າີໄດ" },
                { date: 4, lunar: "ແຮມ 4 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 5, lunar: "ແຮມ 5 ຄ່ຳ ດ. 8", prediction: "ມື້ກົດເສັດ - ໃສ່ເສຍ" },
                { date: 6, lunar: "ແຮມ 6 ຄ່ຳ ດ. 8", prediction: "ມື້ຮ້ວງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 7, lunar: "ແຮມ 7 ຄ່ຳ ດ. 8", prediction: "ມື້ເຕົ່າໃຈ - ສ້ຽວປ່າວ" },
                { date: 8, lunar: "ແຮມ 8 ຄ່ຳ ດ. 8", prediction: "ມື້ກ່າເປົ້າ - ເຕົ້າກອງ", special: "red" },
                { date: 9, lunar: "ແຮມ 9 ຄ່ຳ ດ. 8", prediction: "ມື້ກາບຍີ - ຮອງຟືນ" },
                { date: 10, lunar: "ແຮມ 10 ຄ່ຳ ດ. 8", prediction: "ມື້ດັບເໝົ້າ - ພັນດອກ" },
                { date: 11, lunar: "ແຮມ 11 ຄ່ຳ ດ. 8", prediction: "ມື້ຮາຍສີ - ພັນຕາຍ" },
                { date: 12, lunar: "ແຮມ 12 ຄ່ຳ ດ. 8", prediction: "ມື້ເມັງໃສ້ - ສຸກພັກ" },
                { date: 13, lunar: "ແຮມ 13 ຄ່ຳ ດ. 8", prediction: "ມື້ປືກສະງ້າ - ຮັບໄຊ້" },
                { date: 14, lunar: "ແຮມ 14 ຄ່ຳ ດ. 8", prediction: "ມື້ກັດເມັດ - ຮັບຕາຍ", special: "red" },
                { date: 15, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກົດສັນ - ງົວຕາຍ" },
                { date: 16, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮ້ວງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 17, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເສຍ" },
                { date: 18, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກ່າໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 19, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກາບໃຈ - ສ້ຽວປ່າວ" },
                { date: 20, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 9.1", prediction: "ມື້ດັບເປົ້າ - ເຕົ້າກອງ" },
                { date: 21, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮາຍຍີ - ຮອງຟືນ" },
                { date: 22, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເມັງເໝົ້າ - ພັນດອກ", special: "red" },
                { date: 23, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 9.1", prediction: "ມື້ປືກສີ - ພັນຕາຍ" },
                { date: 24, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກັດໃສ້ - ສຸກພັກ" },
                { date: 25, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກົດສະງ້າ - ຮັບໄຊ້" },
                { date: 26, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮ້ວງເມັດ - ຮັບຕາຍ" },
                { date: 27, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເຕົ່າສັນ - ງົວຕາຍ" },
                { date: 28, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກ່າເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 29, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກາບເສັດ - ໃສ່ເສຍ", special: "red" },
                { date: 30, lunar: "ແຮມ 1 ຄ່ຳ ດ. 9.1", prediction: "ມື້ດັບໄກ້ - ຫົວວາຍປ່າວ" }
            ]
        },
        {
            nameLao: "ກໍລະກົດ",
            nameEng: "JULY",
            headerDetails: "ເດືອນກໍລະກົດ (7) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 3, // Wednesday
            footerText: [
                "13 ວັນເກີດທ່ານສຸພານຸວົງ ຄົບຮອບ 117 ປີ(13/7/1909)",
                "20 ວັນສ້າງຕັ້ງສະຫະພັນແມ່ຍິງລາວຄົບຮອບ 71 ປີ(20/7/1955)",
                "29 ບຸນເຂົ້າພັນສາ",
                "28 ວັນຜູ້ມີອາຍຸອົງການຈັດຕັ້ງສາກົນ (28/7/1959)",
                "30 ມື້ເຂົ້າພັນສາຂອງພະສົງທົ່ວປະເທດ"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 2 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮາຍໃຈ - ສ້ຽວປ່າວ" },
                { date: 2, lunar: "ແຮມ 3 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເມັງເປົ້າ - ເຕົ້າກອງ" },
                { date: 3, lunar: "ແຮມ 4 ຄ່ຳ ດ. 9.1", prediction: "ມື້ປືກຍີ - ຮອງຟືນ" },
                { date: 4, lunar: "ແຮມ 5 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກັດເໝົ້າ - ພັນດອກ" },
                { date: 5, lunar: "ແຮມ 6 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກົດສີ - ພັນຕາຍ" },
                { date: 6, lunar: "ແຮມ 7 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮ້ວງໃສ້ - ສຸກພັກ" },
                { date: 7, lunar: "ແຮມ 8 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເຕົ່າສະງ້າ - ຮັບໄຊ້", special: "red" },
                { date: 8, lunar: "ແຮມ 9 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກ່າເມັດ - ຮັບຕາຍ" },
                { date: 9, lunar: "ແຮມ 10 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກາບສັນ - ງົວຕາຍ" },
                { date: 10, lunar: "ແຮມ 11 ຄ່ຳ ດ. 9.1", prediction: "ມື້ດັບເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 11, lunar: "ແຮມ 12 ຄ່ຳ ດ. 9.1", prediction: "ມື້ຮາຍເສັດ - ໃສ່ເສຍ" },
                { date: 12, lunar: "ແຮມ 13 ຄ່ຳ ດ. 9.1", prediction: "ມື້ເມັງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 13, lunar: "ແຮມ 14 ຄ່ຳ ດ. 9.1", prediction: "ມື້ປືກໃຈ - ສ້ຽວປ່າວ" },
                { date: 14, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 9.1", prediction: "ມື້ກັດເປົ້າ - ເຕົ້າກອງ", special: "red" },
                { date: 15, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກົດຍີ - ຮອງຟືນ" },
                { date: 16, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮ້ວງເໝົ້າ - ພັນດອກ" },
                { date: 17, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເຕົ່າສີ - ພັນຕາຍ" },
                { date: 18, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກ່າໃສ້ - ສຸກພັກ" },
                { date: 19, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກາບສະງ້າ - ຮັບໄຊ້" },
                { date: 20, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 9.2", prediction: "ມື້ດັບເມັດ - ຮັບຕາຍ" },
                { date: 21, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮາຍສັນ - ຄວາຍຕາຍ" },
                { date: 22, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເມັງເລົ້າ - ໃສ່ເຈົ້າ", special: "red" },
                { date: 23, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 9.2", prediction: "ມື້ປືກເສັດ - ໃສ່ເສຍ" },
                { date: 24, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກັດໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 25, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກົດໃຈ - ສ້ຽວປ່າວ" },
                { date: 26, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮ້ວງເປົ້າ - ເຕົ້າກອງ" },
                { date: 27, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເຕົ່າຍີ - ຮອງຟືນ" },
                { date: 28, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກ່າເໝົ້າ - ພັນດອກ" },
                { date: 29, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກາບສີ - ພັນຕາຍ", special: "red" },
                { date: 30, lunar: "ແຮມ 1 ຄ່ຳ ດ. 9.2", prediction: "ມື້ດັບໃສ້ - ສຸກພັກ" },
                { date: 31, lunar: "ແຮມ 2 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮາຍສະງ້າ - ຮັບໄຊ້" }
            ]
        },
        {
            nameLao: "ສິງຫາ",
            nameEng: "AUGUST",
            headerDetails: "ເດືອນສິງຫາ (8) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 6, // Saturday
            footerText: [
                "13 ວັນເກີດທ່ານສຸພານຸວົງ ຄົບຮອບ 117 ປີ(13/7/1909)", // Copied from July image in my analysis? Let me re-check image 2.
                // Image 2 Footer:
                // 13 ວັນເກີດທ່ານສຸພານຸວົງ ຄົບຮອບ 117 ປີ (13/7/1909) (Wait, Month 8 is August. Why July date?)
                // Ah, looking closely at Image 2 footer text... it's the SAME text as Image 0 (July).
                // Wait. Image 0 (July) footer: 13/7/1909...
                // Image 2 (August) footer: 13 ວັນເກີດທ່ານສຸພານຸວົງ... (13/8/1950)
                // Ah, Image 2 footer line 13: 13 ວັນສ້າງຕັ້ງ... (13/8/1950)
                // Let me re-read Image 2 footer carefully.
                // "13 ວັນສ້າງຕັ້ງແນວລາວຮັກຊາດ ຄົບຮອບ 67 ປີ (13/8/1950)"
                // "15 ວັນລັດຖະທຳມະນູນແຫ່ງຊາດຄົບຮອບ 35 ປີ (15/8/1991)"
                // "23 ວັນຢຶດອຳນາດທົ່ວປະເທດຄົບຮອບ 51 ປີ (23/8/1975)"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 3 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເມັງມົດ - ຮັບຕາຍ" },
                { date: 2, lunar: "ແຮມ 4 ຄ່ຳ ດ. 9.2", prediction: "ມື້ປືກສັນ - ຄວ້າີໄດ" },
                { date: 3, lunar: "ແຮມ 5 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກັດເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 4, lunar: "ແຮມ 6 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກົດເສັດ - ໃສ່ເສຍ" },
                { date: 5, lunar: "ແຮມ 7 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮ້ວງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 6, lunar: "ແຮມ 8 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເຕົ່າໃຈ - ສ້ຽວປ່າວ", special: "red" },
                { date: 7, lunar: "ແຮມ 9 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກ່າເປົ້າ - ເຕົ້າກອງ" },
                { date: 8, lunar: "ແຮມ 10 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກາບຍີ - ຮອງຟືນ" },
                { date: 9, lunar: "ແຮມ 11 ຄ່ຳ ດ. 9.2", prediction: "ມື້ດັບເໝົ້າ - ພັນດອກ" },
                { date: 10, lunar: "ແຮມ 12 ຄ່ຳ ດ. 9.2", prediction: "ມື້ຮາຍສີ - ພັນຕາຍ" },
                { date: 11, lunar: "ແຮມ 13 ຄ່ຳ ດ. 9.2", prediction: "ມື້ເມັງໃສ້ - ສຸກພັກ" },
                { date: 12, lunar: "ແຮມ 14 ຄ່ຳ ດ. 9.2", prediction: "ມື້ປືກສະງ້າ - ຮັບໄຊ້" },
                { date: 13, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 9.2", prediction: "ມື້ກັດເມັດ - ຮັບຕາຍ", special: "red" },
                { date: 14, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 10", prediction: "ມື້ກົດສັນ - ງົວຕາຍ" },
                { date: 15, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 10", prediction: "ມື້ຮ້ວງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 16, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 10", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເສຍ" },
                { date: 17, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 10", prediction: "ມື້ກ່າໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 18, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 10", prediction: "ມື້ກາບໃຈ - ສ້ຽວປ່າວ" },
                { date: 19, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 10", prediction: "ມື້ດັບເປົ້າ - ເຕົ້າກອງ" },
                { date: 20, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 10", prediction: "ມື້ຮາຍຍີ - ຮອງຟືນ" },
                { date: 21, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 10", prediction: "ມື້ເມັງເໝົ້າ - ພັນດອກ", special: "red" },
                { date: 22, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 10", prediction: "ມື້ປືກສີ - ພັນຕາຍ" },
                { date: 23, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 10", prediction: "ມື້ກັດໃສ້ - ສຸກພັກ" },
                { date: 24, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 10", prediction: "ມື້ກົດສະງ້າ - ຮັບໄຊ້" },
                { date: 25, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 10", prediction: "ມື້ຮ້ວງເມັດ - ຮັບຕາຍ" },
                { date: 26, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 10", prediction: "ມື້ເຕົ່າສັນ - ງົວຕາຍ" },
                { date: 27, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 10", prediction: "ມື້ກ່າເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 28, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 10", prediction: "ມື້ກາບເສັດ - ໃສ່ເສຍ", special: "red" },
                { date: 29, lunar: "ແຮມ 1 ຄ່ຳ ດ. 10", prediction: "ມື້ດັບໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 30, lunar: "ແຮມ 2 ຄ່ຳ ດ. 10", prediction: "ມື້ຮາຍໃຈ - ສ້ຽວປ່າວ" },
                { date: 31, lunar: "ແຮມ 3 ຄ່ຳ ດ. 10", prediction: "ມື້ເມັງເປົ້າ - ເຕົ້າກອງ" }
            ]
        },
        {
            nameLao: "ກັນຍາ",
            nameEng: "SEPTEMBER",
            headerDetails: "ເດືອນກັນຍາ (9) ປີມະເມັຍ. ປີຮັບໃຊ້. ສັດຕະສັກ. ອະທິກະມາດ, ປົກກະຕິວານ, ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 2, // Tuesday
            footerText: [
                "11 ບຸນຫໍ່ເຂົ້າປະດັບດິນ",
                "26 ບຸນຫໍ່ເຂົ້າສະລາກ"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 4 ຄ່ຳ ດ. 10", prediction: "ມື້ປືກຍີ - ຮອງຟືນ" },
                { date: 2, lunar: "ແຮມ 5 ຄ່ຳ ດ.10", prediction: "ມື້ກັດເໝົ້າ - ພັນດອກ" },
                { date: 3, lunar: "ແຮມ 6 ຄ່ຳ ດ. 10", prediction: "ມື້ກົດສີ - ພັນຕາຍ" },
                { date: 4, lunar: "ແຮມ 7 ຄ່ຳ ດ. 10", prediction: "ມື້ຮ້ວງໃສ້ - ສຸກພັກ" },
                { date: 5, lunar: "ແຮມ 8 ຄ່ຳ ດ. 10", prediction: "ມື້ເຕົ່າສະງ້າ - ຮັບໄຊ້", special: "red" },
                { date: 6, lunar: "ແຮມ 9 ຄ່ຳ ດ. 10", prediction: "ມື້ກ່າເມັດ - ຮັບຕາຍ" },
                { date: 7, lunar: "ແຮມ 10 ຄ່ຳ ດ. 10", prediction: "ມື້ກາບສັນ - ໃສ່ແສ້" },
                { date: 8, lunar: "ແຮມ 11 ຄ່ຳ ດ. 10", prediction: "ມື້ດັບເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 9, lunar: "ແຮມ 12 ຄ່ຳ ດ. 10", prediction: "ມື້ຮາຍເສັດ - ໃສ່ເສຍ" },
                { date: 10, lunar: "ແຮມ 13 ຄ່ຳ ດ. 10", prediction: "ມື້ເມັງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 11, lunar: "ແຮມ 14 ຄ່ຳ ດ. 10", prediction: "ມື້ປືກໃຈ - ສ້ຽວປ່າວ", special: "red" },
                { date: 12, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 11", prediction: "ມື້ກັດເປົ້າ - ເຕົ້າກອງ" },
                { date: 13, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 11", prediction: "ມື້ກົດຍີ - ຮອງຟືນ" },
                { date: 14, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 11", prediction: "ມື້ຮ້ວງເໝົ້າ - ພັນດອກ" },
                { date: 15, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 11", prediction: "ມື້ເຕົ່າສີ - ພັນຕາຍ" },
                { date: 16, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 11", prediction: "ມື້ກ່າໃສ້ - ສຸກພັກ" },
                { date: 17, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 11", prediction: "ມື້ກາບສະງ້າ - ຮັບໄຊ້" },
                { date: 18, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 11", prediction: "ມື້ດັບເມັດ - ຮັບຕາຍ" },
                { date: 19, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 11", prediction: "ມື້ຮາຍສັນ - ຄວາຍຕາຍ", special: "red" },
                { date: 20, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 11", prediction: "ມື້ເມັງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 21, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 11", prediction: "ມື້ປືກເສັດ - ໃສ່ເສຍ" },
                { date: 22, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 11", prediction: "ມື້ກັດໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 23, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 11", prediction: "ມື້ກົດໃຈ - ສ້ຽວປ່າວ" },
                { date: 24, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 11", prediction: "ມື້ຮ້ວງເປົ້າ - ເຕົ້າກອງ" },
                { date: 25, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 11", prediction: "ມື້ເຕົ່າຍີ - ຮອງຟືນ" },
                { date: 26, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 11", prediction: "ມື້ກ່າເໝົ້າ - ພັນດອກ", special: "red" },
                { date: 27, lunar: "ແຮມ 1 ຄ່ຳ ດ. 11", prediction: "ມື້ກາບສີ - ພັນຕາຍ" },
                { date: 28, lunar: "ແຮມ 2 ຄ່ຳ ດ. 11", prediction: "ມື້ດັບໃສ້ - ສຸກພັກ" },
                { date: 29, lunar: "ແຮມ 3 ຄ່ຳ ດ. 11", prediction: "ມື້ຮາຍສະງ້າ - ຮັບໄຊ້" },
                { date: 30, lunar: "ແຮມ 4 ຄ່ຳ ດ. 11", prediction: "ມື້ເມັງມົດ - ຮັບຕາຍ" }
            ]
        },
        {
            nameLao: "ຕຸລາ",
            nameEng: "OCTOBER",
            headerDetails: "ເດືອນຕຸລາ (10) . ປີມະເມັຍ, ປີຮັບໃຊ້. ມັງກະສັກ. ອະທິກະມາດ. ປົກກະຕິວານ ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ 2026",
            startDay: 4, // Thursday
            footerText: [
                "7 ວັນຄູແຫ່ງຊາດຄົບຮອບ 32 ປີ(7/10/1994 ແລະ ວັນສ້າງຕັ້ງທະນາຄານ ແຫ່ງ ສປປ ລາວ)",
                "12 ວັນປະກາດເອກະລາດ ຄົບຮອບ 81 ປີ(12/10/1945)",
                "26 ບຸນອອກພັນສາ ປະວໍລະນາ",
                "27 ວັນຊ່ວງເຮືອ ຢູ່ງວງທະນະຄອນຫຼວງວຽງຈັນ",
                "28 ຕັກບາດວຽນທຽນ ຢູ່ນະຄອນຫຼວງວຽງຈັນ"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 5 ຄ່ຳ ດ. 11", prediction: "ມື້ປືກສັນ - ຄວ້າີໄດ" },
                { date: 2, lunar: "ແຮມ 6 ຄ່ຳ ດ.11", prediction: "ມື້ກັດເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 3, lunar: "ແຮມ 7 ຄ່ຳ ດ. 11", prediction: "ມື້ກົດເສັດ - ໃສ່ເສຍ" },
                { date: 4, lunar: "ແຮມ 8 ຄ່ຳ ດ. 11", prediction: "ມື້ຮ້ວງໄກ້ - ຫົວວາຍປ່າວ", special: "red" },
                { date: 5, lunar: "ແຮມ 9 ຄ່ຳ ດ. 11", prediction: "ມື້ເຕົ່າໃຈ - ສ້ຽວປ່າວ" },
                { date: 6, lunar: "ແຮມ 10 ຄ່ຳ ດ. 11", prediction: "ມື້ກ່າເປົ້າ - ເຕົ້າກອງ" },
                { date: 7, lunar: "ແຮມ 11 ຄ່ຳ ດ. 11", prediction: "ມື້ກາບຍີ - ຮອງຟືນ" },
                { date: 8, lunar: "ແຮມ 12 ຄ່ຳ ດ. 11", prediction: "ມື້ດັບເໝົ້າ - ພັນດອກ" },
                { date: 9, lunar: "ແຮມ 13 ຄ່ຳ ດ. 11", prediction: "ມື້ຮາຍສີ - ພັນຕາຍ" },
                { date: 10, lunar: "ແຮມ 14 ຄ່ຳ ດ. 11", prediction: "ມື້ເມັງໃສ້ - ສຸກພັກ" },
                { date: 11, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 11", prediction: "ມື້ປືກສະງ້າ - ຮັບໄຊ້", special: "red" },
                { date: 12, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. 12", prediction: "ມື້ກັດເມັດ - ຮັບຕາຍ" },
                { date: 13, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. 12", prediction: "ມື້ກົດສັນ - ງົວຕາຍ" },
                { date: 14, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. 12", prediction: "ມື້ຮ້ວງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 15, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. 12", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເສຍ" },
                { date: 16, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. 12", prediction: "ມື້ກ່າໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 17, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. 12", prediction: "ມື້ກາບໃຈ - ສ້ຽວປ່າວ" },
                { date: 18, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. 12", prediction: "ມື້ດັບເປົ້າ - ເຕົ້າກອງ", special: "red" },
                { date: 19, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. 12", prediction: "ມື້ຮາຍຍີ - ຮອງຟືນ", special: "red" },
                { date: 20, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. 12", prediction: "ມື້ເມັງເໝົ້າ - ພັນດອກ" },
                { date: 21, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. 12", prediction: "ມື້ປືກສີ - ພັນຕາຍ" },
                { date: 22, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. 12", prediction: "ມື້ກັດໃສ້ - ສຸກພັກ" },
                { date: 23, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. 12", prediction: "ມື້ກົດສະງ້າ - ຮັບໄຊ້" },
                { date: 24, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. 12", prediction: "ມື້ຮ້ວງເມັດ - ຮັບຕາຍ" },
                { date: 25, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. 12", prediction: "ມື້ເຕົ່າສັນ - ງົວຕາຍ" },
                { date: 26, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. 12", prediction: "ມື້ກ່າເລົ້າ - ໃສ່ເຈົ້າ", special: "red" },
                { date: 27, lunar: "ແຮມ 1 ຄ່ຳ ດ. 12", prediction: "ມື້ກາບເສັດ - ໃສ່ເສຍ" },
                { date: 28, lunar: "ແຮມ 2 ຄ່ຳ ດ. 12", prediction: "ມື້ດັບໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 29, lunar: "ແຮມ 3 ຄ່ຳ ດ. 12", prediction: "ມື້ຮາຍໃຈ - ສ້ຽວປ່າວ" },
                { date: 30, lunar: "ແຮມ 4 ຄ່ຳ ດ. 12", prediction: "ມື້ເມັງເປົ້າ - ເຕົ້າກອງ" },
                { date: 31, lunar: "ແຮມ 5 ຄ່ຳ ດ. 12", prediction: "ມື້ປືກຍີ - ຮອງຟືນ" }
            ]
        },
        {
            nameLao: "ພະຈິກ",
            nameEng: "NOVEMBER",
            headerDetails: "ເດືອນພະຈິກ (11) . ປີມະເມັຍ, ປີຮັບໃຊ້. ມັງກະສັກ. ອະທິກະມາດ. ປົກກະຕິວານ ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 0, // Sunday
            footerText: [
                "20 ວັນສິດທິເດັກ ຄົບຮອບ 81 ປີ (20/11/1945)",
                "24 ບຸນນະມັດສະການພະທາດຫຼວງ ເມືອງໄຊ ເຂວງອຸດົມໄຊ",
                "24 ບຸນນະມັດສະການພະທາດຫຼວງ",
                "02/11/2010 ວັນປະກົດສະການພະຈັນເຈົ້າອະນຸວົງ" // Check image text carefully. It says "ວັນປະດິດສະຖານພະເຈົ້າອະນຸວົງ" perhaps? Image 1 footer last line.
                // Image says: 02/11/2010 ວັນປະດິດສະຖານພະເຈົ້າອະນຸວົງ
            ],
            days: [
                { date: 1, lunar: "ແຮມ 6 ຄ່ຳ ດ. 12", prediction: "ມື້ກັດເໝົ້າ - ພັນດອກ" },
                { date: 2, lunar: "ແຮມ 7 ຄ່ຳ ດ.12", prediction: "ມື້ກົດສີ - ພັນຕາຍ" },
                { date: 3, lunar: "ແຮມ 8 ຄ່ຳ ດ. 12", prediction: "ມື້ຮ້ວງໃສ້ - ສຸກພັກ", special: "red" },
                { date: 4, lunar: "ແຮມ 9 ຄ່ຳ ດ. 12", prediction: "ມື້ເຕົ່າສະງ້າ - ຮັບໄຊ້" },
                { date: 5, lunar: "ແຮມ 10 ຄ່ຳ ດ. 12", prediction: "ມື້ກ່າເມັດ - ຮັບຕາຍ" },
                { date: 6, lunar: "ແຮມ 11 ຄ່ຳ ດ. 12", prediction: "ມື້ກາບສັນ - ງົວຕາຍ" },
                { date: 7, lunar: "ແຮມ 12 ຄ່ຳ ດ. 12", prediction: "ມື້ດັບເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 8, lunar: "ແຮມ 13 ຄ່ຳ ດ. 12", prediction: "ມື້ຮາຍເສັດ - ໃສ່ເສຍ" },
                { date: 9, lunar: "ແຮມ 14 ຄ່ຳ ດ. 12", prediction: "ມື້ເມັງໄກ້ - ຫົວວາຍປ່າວ", special: "red" },
                { date: 10, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ປືກໃຈ - ສ້ຽວປ່າວ" }, // D. Jiang (Month 1, Tribal year change?) Image says "ດ. ຈຽງ"
                { date: 11, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກັດເປົ້າ - ເຕົ້າກອງ" },
                { date: 12, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກົດຍີ - ຮອງຟືນ" },
                { date: 13, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮ້ວງເໝົ້າ - ພັນດອກ" },
                { date: 14, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເຕົ່າສີ - ພັນຕາຍ" },
                { date: 15, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກ່າໃສ້ - ສຸກພັກ" },
                { date: 16, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກາບສະງ້າ - ຮັບໄຊ້" },
                { date: 17, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ດັບເມັດ - ຮັບຕາຍ", special: "red" },
                { date: 18, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮາຍສັນ - ງົວຕາຍ" },
                { date: 19, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເມັງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 20, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ປືກເສັດ - ໃສ່ເສຍ" },
                { date: 21, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກັດໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 22, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກົດໃຈ - ສ້ຽວປ່າວ" },
                { date: 23, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮ້ວງເປົ້າ - ເຕົ້າກອງ" },
                { date: 24, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເຕົ່າຍີ - ຮອງຟືນ", special: "red" },
                { date: 25, lunar: "ແຮມ 1 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກ່າເໝົ້າ - ພັນດອກ" },
                { date: 26, lunar: "ແຮມ 2 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກາບສີ - ພັນຕາຍ" },
                { date: 27, lunar: "ແຮມ 3 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ດັບໃສ້ - ສຸກພັກ" },
                { date: 28, lunar: "ແຮມ 4 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮາຍສະງ້າ - ຮັບໄຊ້" },
                { date: 29, lunar: "ແຮມ 5 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເມັງມົດ - ຮັບຕາຍ" },
                { date: 30, lunar: "ແຮມ 6 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ປືກສັນ - ງົວຕາຍ" }
            ]
        },
        {
            nameLao: "ທັນວາ",
            nameEng: "DECEMBER",
            headerDetails: "ເດືອນທັນວາ (12) . ປີມະເມັຍ, ປີຮັບໃຊ້. ມັງກະສັກ. ອະທິກະມາດ. ປົກກະຕິວານ ປົກກະຕິລຶກຖິນ ພ.ສ. 2569- ຈ.ສ.1388. ຄ.ສ. 2026",
            startDay: 2, // Tuesday
            footerText: [
                "2 ວັນສະຖາປະນາ ສ.ປ.ປ.ລາວ ຄົບຮອບ 51 ປີ (2/12/1975)",
                "6 ວັນສ້າງຕັ້ງສະຫະພັນນັກຮົບເກົ່າຄົບຮອບ 37 ປີ (6/12/1989)",
                "13 ວັນເກີດປະທານໄກສອນ ພົມວິຫານ ຄົບຮອບ 106 ປີ (13/12/1920)"
            ],
            days: [
                { date: 1, lunar: "ແຮມ 7 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກັດເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 2, lunar: "ແຮມ 8 ຄ່ຳ ດ.ຈຽງ", prediction: "ມື້ກົດເສັດ - ໃສ່ເສຍ", special: "red" },
                { date: 3, lunar: "ແຮມ 9 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮ້ວງໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 4, lunar: "ແຮມ 10 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເຕົ່າໃຈ - ສ້ຽວປ່າວ" },
                { date: 5, lunar: "ແຮມ 11 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກ່າເປົ້າ - ເຕົ້າກອງ" },
                { date: 6, lunar: "ແຮມ 12 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ກາບຍີ - ຮອງຟືນ" },
                { date: 7, lunar: "ແຮມ 13 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ດັບເໝົ້າ - ພັນດອກ" },
                { date: 8, lunar: "ແຮມ 14 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ຮາຍສີ - ພັນຕາຍ" },
                { date: 9, lunar: "ແຮມ 15 ຄ່ຳ ດ. ຈຽງ", prediction: "ມື້ເມັງໃສ້ - ສຸກພັກ", special: "red" },
                { date: 10, lunar: "ຂຶ້ນ 1 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ປືກສະງ້າ - ຮັບໄຊ້" },
                { date: 11, lunar: "ຂຶ້ນ 2 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກັດເມັດ - ຮັບຕາຍ" },
                { date: 12, lunar: "ຂຶ້ນ 3 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກົດສັນ - ງົວຕາຍ" },
                { date: 13, lunar: "ຂຶ້ນ 4 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ຮ້ວງເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 14, lunar: "ຂຶ້ນ 5 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ເຕົ່າເສັດ - ໃສ່ເສຍ" },
                { date: 15, lunar: "ຂຶ້ນ 6 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກ່າໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 16, lunar: "ຂຶ້ນ 7 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກາບໃຈ - ສ້ຽວປ່າວ" },
                { date: 17, lunar: "ຂຶ້ນ 8 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ດັບເປົ້າ - ເຕົ້າກອງ", special: "red" },
                { date: 18, lunar: "ຂຶ້ນ 9 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ຮາຍຍີ - ຮອງຟືນ" },
                { date: 19, lunar: "ຂຶ້ນ 10 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ເມັງເໝົ້າ - ພັນດອກ" },
                { date: 20, lunar: "ຂຶ້ນ 11 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ປືກສີ - ພັນຕາຍ" },
                { date: 21, lunar: "ຂຶ້ນ 12 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກັດໃສ້ - ສຸກພັກ" },
                { date: 22, lunar: "ຂຶ້ນ 13 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກົດສະງ້າ - ຮັບໄຊ້" },
                { date: 23, lunar: "ຂຶ້ນ 14 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ຮ້ວງເມັດ - ຮັບຕາຍ" },
                { date: 24, lunar: "ຂຶ້ນ 15 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ເຕົ່າສັນ - ງົວຕາຍ", special: "red" },
                { date: 25, lunar: "ແຮມ 1 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກ່າເລົ້າ - ໃສ່ເຈົ້າ" },
                { date: 26, lunar: "ແຮມ 2 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກາບເສັດ - ໃສ່ເສຍ" },
                { date: 27, lunar: "ແຮມ 3 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ດັບໄກ້ - ຫົວວາຍປ່າວ" },
                { date: 28, lunar: "ແຮມ 4 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ຮາຍໃຈ - ສ້ຽວປ່າວ" },
                { date: 29, lunar: "ແຮມ 5 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ເມັງເປົ້າ - ເຕົ້າກອງ" },
                { date: 30, lunar: "ແຮມ 6 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ປືກຍີ - ຮອງຟືນ" },
                { date: 31, lunar: "ແຮມ 7 ຄ່ຳ ດ. ຍີ່", prediction: "ມື້ກັດເໝົ້າ - ພັນດອກ" }
            ]
        }
    ]
};
